apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
spec:
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext: {}
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      containers:
      - name: rest
        image: kyndryl.jfrog.io/uki-business-intelligence-test-docker-local/rest:dev_${{ github.run_number }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 32m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
        terminationMessagePolicy: File
        env:
        - name: PORT
          value: "8080"
        - name: TEMP_INLINE_VALUE
          # we can also pass env variables like in this way 
          value: Linux
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            # name: rest-app-docker-secrets-generic
            name: env-secrets
