apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: REST
    type: internal-apps-001
  name: rest-route
  namespace: {{ .Values.nameOverride }}
  annotations:
    description: Route for REST Production instance.
    haproxy.router.openshift.io/timeout: 3600s
spec:
  host: {{ .Values.hostUrlOverride }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rest-svc
