apiVersion: v1
kind: Service
metadata:
  name: rest-svc
  labels:
    app: rest
spec:
  type: {{ .Values.service.type }}
  selector:
    app: rest
  ports:
  - name: rest-svc-port
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
