--<ScriptOptions statementTerminator=";"/>
DROP TABLE "REST"."DB2_ERRORS";

CREATE TABLE "REST"."DB2_ERRORS" (
		"USERID" CHAR(50) DEFAULT NULL,
		"PAGE" VARCHAR(300) DEFAULT NULL,
		"DB2_ERROR" CHAR(50) DEFAULT NULL,
		"DB2_MESSAGE" VARCHAR(512) DEFAULT NULL,
		"BACKTRACE" CLOB(2048) DEFAULT NULL,
		"REQUEST" VARCHAR(1024) DEFAULT NULL,
		"TIMESTAMP" TIMESTAMP DEFAULT CURRENT TIMESTAMP
	)
	DATA CAPTURE NONE;

